# バックエンド用ビルド

steps:
  # PROJECT_ID は Secret Manager から取得している
  
  # gcr.io へ Docker イメージをアップ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PROJECT_ID=$(gcloud secrets versions access latest --secret=my_location_monitor_project_id)
        echo "Using PROJECT_ID: $PROJECT_ID"

        gcloud builds submit --tag gcr.io/$PROJECT_ID/backend backend

  # gcr.io へ Docker イメージでデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PROJECT_ID=$(gcloud secrets versions access latest --secret=my_location_monitor_project_id)
        echo "Deploying to Cloud Run with PROJECT_ID: $PROJECT_ID"

        gcloud run deploy backend \
          --image gcr.io/$PROJECT_ID/backend \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

images:
  - 'gcr.io/$PROJECT_ID/backend'
